databases:
  - name: api_db
    plan: free
    databaseName: api_db
    user: api_db

services:
  - type: web
    name: django-rest-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rest_api.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: rest_api.settings
