databases:
  - name: api_db
    plan: free
    databaseName: api_db
    user: api_db

services:
  - type: web
    name: api
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rest_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true

envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: api_db
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  - key: WEB_CONCURRENCY
    value: 2
  - key: DJANGO_SUPERUSER_PASSWORD
    generateValue: true
  - key: DJANGO_SETTINGS_MODULE # これを追加
    value: rest_api.settings # settings.py へのパス。必要に応じて変更
